### ISSUE TITLE
Replier not showing when using eloquent branch

### ISSUE THREAD

**Issue by eranroll** [eProsima/Micro-XRCE-DDS-Agent#229]
Hi,

I have a client which is publishing ROS services over Micro XRCEDDS on an M7 MCU.
When I load an agent based on the dashing branch, repliers and requesters work just fine. However, when I move to the eloquent branch it doesn't.

However, publishers and subscribers are shown and work as expected.

Regards

**Comment by jamoralp** [comment]
Good morning @eranroll ,

I think somehow that branch got lost under our development process. It should definitely not be there. Anyway, it is a `feature` branch so it does not surprise me that you are having trouble.

The official ROS 2 versions that we support, and that are up-to-date, are Dashing and Foxy. This is because the micro-ROS Agent uses this branches as a base. Anyway, it is not mandatory to switch to a ROS branch to use the agent for ROS 2 related purposes,
You can just compile the agent provided in master branch, and it should work just fine.

Regards,

**Comment by jamoralp** [comment]
I am going to close this. Please test the agent in the master branch, or try our docker image `eprosima/micro-xrce-dds-agent`. Reopen if you have any other problem. thanks!
